
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - nesting
  - vertical_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - redundant_nil_coalescing
  - private_outlet
  - private_action
  - unneeded_parentheses_in_closure_argument
  - operator_usage_whitespace
  - sorted_imports
  - switch_case_on_newline
  - unneeded_break_in_switch
  - number_separator
  - object_literal
  - prohibited_super_call
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - fallthrough
  - discouraged_object_literal
  - discouraged_direct_init
  - first_where
  - for_where
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - no_space_in_method_call
  - operator_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_unit_test
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - single_test_class
  - strict_fileprivate
  - unavailable_function
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - xct_specific_matcher
  - yoda_condition
excluded:
  - Pods
  - Gifty_iOS/Resources/
  - Gifty_iOS/Sources/DesignSystem/Font/
analyzer_rules:
  - explicit_self
